version: '2'   
services:
  cuda-toolkit:
    build: ./cuda-toolkit
    privileged: true
    devices:
      - "/dev/nvhost-ctrl-gpu:/dev/nvhost-ctrl-gpu"
      - "/dev/nvmap:/dev/nvmap"
      - "/dev/nvhost-dbg-gpu:/dev/nvhost-dbg-gpu"
      - "/dev/nvhost-prof-gpu:/dev/nvhost-prof-gpu"
      - "/dev/nvhost-ctrl:/dev/nvhost-ctrl"
      - "/dev/shm:/dev/shm"      
  tensorrt:
    build: ./tensorrt
    privileged: true
  pytorch:
    build: ./pytorch
    privileged: true
  tensorflow:
    build: ./tensorflow
    privileged: true
  deepstream:
    build: ./deepstream
    privileged: true
    network_mode: "host"
