version: '2'

volumes:
    sample-data:
    
services:

  cuda-toolkit:
    build: ./cuda-toolkit
    #image: nvcr.io/nvidia/l4t-base:r32.5.0
    privileged: true
    devices:
      - "/dev/nvhost-ctrl-gpu:/dev/nvhost-ctrl-gpu"
      - "/dev/nvmap:/dev/nvmap"
      - "/dev/nvhost-dbg-gpu:/dev/nvhost-dbg-gpu"
      - "/dev/nvhost-prof-gpu:/dev/nvhost-prof-gpu"
      - "/dev/nvhost-ctrl:/dev/nvhost-ctrl"
      - "/dev/shm:/dev/shm"
    volumes:
      - "sample-data:/data/samples"
